# Generated by Django 4.0.3 on 2022-04-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='expertdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('country', models.TextField(max_length=30)),
                ('prediction', models.TextField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
